version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/trendtalk
      - SPRING_REDIS_URL=redis://default:AUsmAAIjcDEwZjg0NTRkOTE0ZTA0OGM5OTE5ZDVmNjQ4YTM5OTYyNHAxMA@driving-feline-19238.upstash.io:6379
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    container_name: trendtalk-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  chat-server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    container_name: trendtalk-chat
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/trendtalk
    depends_on:
      - mongo
    volumes:
      - ./chat-server:/app
    restart: unless-stopped

volumes:
  mongo-data:
